fix: working!
- use sh shebang line
- simplify run script
- add ghost user to image

Signed-off-by: Kenneth Lim <kennethlimcp@gmail.com>

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,27 +1,31 @@
-dataDir="/Users/kennethlimcp/Desktop/ghost-1.0"
-blogDir="/ghost/blog"
-GHOST_VERSION="1.0.0"
-containerName="ghostblog"
+#!/bin/bash
+
+dataDir="/mnt/usbdrive/ghost-1.0/content"
+blogDir="/var/lib/ghost/content"
+GHOST_VERSION="1.17.3"
 
 docker pull kennethlimcp/armhf-ghost:$GHOST_VERSION
 
-docker rm -f $containerName
+if [ $? -ne 0 ]
+then
+  echo "unable to download image"
+  exit
+fi
+
+docker rm -f ghostblog
 
 docker run --rm \
 --name ghostmigrate \
--v  $dataDir/config.production.json:$blogDir/config.production.json \
--v  $dataDir/content:$blogDir/content \
--e "paths__contentPath=$blogDir/content" \
+-v  $dataDir:$blogDir \
 -e "NODE_ENV=production" \
 kennethlimcp/armhf-ghost:$GHOST_VERSION \
 ghost setup migrate
 
 docker run -d \
 -p 8080:2368 \
---name $containerName \
--v  $dataDir/config.production.json:$blogDir/config.production.json \
--v  $dataDir/content:$blogDir/content \
--e "paths__contentPath=$blogDir/content" \
--e "NODE_ENV=production" \
-kennethlimcp/armhf-ghost:$GHOST_VERSION \
-node current/index.js
+--restart=always \
+--name ghostblog \
+-v  $dataDir:$blogDir \
+kennethlimcp/armhf-ghost:$GHOST_VERSION
+
+docker logs -f ghostblog
